FROM python:alpine3.10
COPY . /app
WORKDIR /app
RUN apk add --no-cache postgresql-libs
RUN apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev
RUN python3 -m pip install -r requirements.txt --no-cache-dir
RUN apk --purge del .build-deps
# RUN pip install -r requirements.txt
EXPOSE 5000
CMD python ./main.py